### ISSUE TITLE
Estructura para componentes con imágenes

### ISSUE THREAD

**Issue by shelldandy** [donmango/tlaxcala#3]
En vez de aventar todas las imágenes en `public/images/`

Recomiendo esta sub-estructura en tus componentes:

Por ej: vamos a hacer servicios se vería así:

```
# src/

├── App.js
├── components
│   ├── BtnService.js
│   ├── Services
│             ├── index.js
│             ├── image-1.jpg
│             ├── image-2.jpg
│             └── iimage-3.jpg
│   └── WhoWeAre.js
├── index.js
└── style.js
```

Entooonces pues como el archivo se llama index dentro de la carpeta del nombre del componente pues lo puedes importar normal.

La clave de tener así las imágenes son 2: una que pues agrupamos concerns y 2:

Que hagas tipo esto:

```js
import image1 from './image-1.jpg'

export default () => (
  <div>
    <img src={image1} />
  </div>
)
```
Así el webpack puede procesar un poco las imágenes y las que no son tan pesadas las mete a base 64 💅

**Comment by jimmylagp** [comment]
Cuando empuje checa si te parece como reestructuré todo.
