### ISSUE TITLE
Usar standard linter

### ISSUE THREAD

**Issue by shelldandy** [donmango/tlaxcala#4]
Paso 1)
```
npm install standard --global
```

(Paso 1.5 para dejarlo local explícito igual)
```
yarn add standard
```

Paso 2:
https://standardjs.com/index.html#are-there-text-editor-plugins

Instala tu plugin en el editor para que veas que show.

Paso 3:
Corregir errores en calor

```
standard --fix /src/**/*.js
```

Los que no pueda te va a avisar y ya en tu IDE los vas viendo

**Comment by jimmylagp** [comment]
Buen consejo.
